/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mantenimientos;

import java.awt.Color;

/**
 *
 * @author Duanel
 */
public class Departamentos extends javax.swing.JFrame {

    /**
     * Creates new form Departamentos
     */
    public Departamentos() {
        initComponents();
        
        setLocationRelativeTo(null); // Centra la ventana en la pantalla.
        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30)); //Redondea Bordes de la ventana Jframe
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Permite que solo se cierre la ventana
        
        //Colores Transparentes para los campos
        txtIDDep.setBackground(new Color(0, 0, 0, 0));
        txtDescDep.setBackground(new Color(0, 0, 0, 0));
        txtEstado.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelesBordesRedondeados1 = new Utilidades.PanelesBordesRedondeados();
        sdrIDDep = new javax.swing.JSeparator();
        txtEstado = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblDescDep = new javax.swing.JLabel();
        sdrCampoDescDep = new javax.swing.JSeparator();
        txtDescDep = new javax.swing.JPasswordField();
        lblIDDep = new javax.swing.JLabel();
        lblBotonRegistrar = new Utilidades.PanelesBordesRedondeados();
        btnInicioSesion2 = new javax.swing.JButton();
        lblBotonEliminar = new Utilidades.PanelesBordesRedondeados();
        btnInicioSesion1 = new javax.swing.JButton();
        txtIDDep = new javax.swing.JTextField();
        lblBtnSalir = new Utilidades.PanelesBordesRedondeados();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(588, 450));
        setResizable(false);

        panelesBordesRedondeados1.setBackground(new java.awt.Color(76, 86, 106));
        panelesBordesRedondeados1.setEnabled(false);
        panelesBordesRedondeados1.setFocusable(false);
        panelesBordesRedondeados1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelesBordesRedondeados1.add(sdrIDDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 100, 10));

        txtEstado.setEditable(false);
        txtEstado.setBackground(new java.awt.Color(255, 204, 102));
        txtEstado.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(236, 239, 244));
        txtEstado.setText("Creando");
        txtEstado.setBorder(null);
        txtEstado.setEnabled(false);
        txtEstado.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtEstado.setName(""); // NOI18N
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEstadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });
        panelesBordesRedondeados1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 100, 40));

        lblUsuario.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(236, 239, 244));
        lblUsuario.setText("Estado:");
        panelesBordesRedondeados1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        lblDescDep.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblDescDep.setForeground(new java.awt.Color(236, 239, 244));
        lblDescDep.setText("Desc. del Departamento");
        panelesBordesRedondeados1.add(lblDescDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        panelesBordesRedondeados1.add(sdrCampoDescDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 240, 10));

        txtDescDep.setBackground(new java.awt.Color(255, 0, 102));
        txtDescDep.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtDescDep.setForeground(new java.awt.Color(236, 239, 244));
        txtDescDep.setBorder(null);
        txtDescDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescDepActionPerformed(evt);
            }
        });
        txtDescDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescDepKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescDepKeyTyped(evt);
            }
        });
        panelesBordesRedondeados1.add(txtDescDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, 40));

        lblIDDep.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblIDDep.setForeground(new java.awt.Color(236, 239, 244));
        lblIDDep.setText("ID del departamento");
        panelesBordesRedondeados1.add(lblIDDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        lblBotonRegistrar.setBackground(new java.awt.Color(59, 66, 82));
        lblBotonRegistrar.setPreferredSize(new java.awt.Dimension(132, 40));
        lblBotonRegistrar.setRoundBottomLeft(20);
        lblBotonRegistrar.setRoundBottomRight(20);
        lblBotonRegistrar.setRoundTopLeft(20);
        lblBotonRegistrar.setRoundTopRight(20);

        btnInicioSesion2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnInicioSesion2.setForeground(new java.awt.Color(204, 204, 204));
        btnInicioSesion2.setText("Registrar");
        btnInicioSesion2.setBorder(null);
        btnInicioSesion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicioSesion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioSesion2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInicioSesion2MousePressed(evt);
            }
        });
        btnInicioSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesion2ActionPerformed(evt);
            }
        });
        btnInicioSesion2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnInicioSesion2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lblBotonRegistrarLayout = new javax.swing.GroupLayout(lblBotonRegistrar);
        lblBotonRegistrar.setLayout(lblBotonRegistrarLayout);
        lblBotonRegistrarLayout.setHorizontalGroup(
            lblBotonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBotonRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicioSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lblBotonRegistrarLayout.setVerticalGroup(
            lblBotonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBotonRegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInicioSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelesBordesRedondeados1.add(lblBotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        lblBotonEliminar.setBackground(new java.awt.Color(59, 66, 82));
        lblBotonEliminar.setPreferredSize(new java.awt.Dimension(132, 40));
        lblBotonEliminar.setRoundBottomLeft(20);
        lblBotonEliminar.setRoundBottomRight(20);
        lblBotonEliminar.setRoundTopLeft(20);
        lblBotonEliminar.setRoundTopRight(20);

        btnInicioSesion1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnInicioSesion1.setForeground(new java.awt.Color(204, 204, 204));
        btnInicioSesion1.setText("Eliminar");
        btnInicioSesion1.setBorder(null);
        btnInicioSesion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicioSesion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioSesion1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInicioSesion1MousePressed(evt);
            }
        });
        btnInicioSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesion1ActionPerformed(evt);
            }
        });
        btnInicioSesion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnInicioSesion1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lblBotonEliminarLayout = new javax.swing.GroupLayout(lblBotonEliminar);
        lblBotonEliminar.setLayout(lblBotonEliminarLayout);
        lblBotonEliminarLayout.setHorizontalGroup(
            lblBotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBotonEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicioSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lblBotonEliminarLayout.setVerticalGroup(
            lblBotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBotonEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInicioSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelesBordesRedondeados1.add(lblBotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        txtIDDep.setBackground(new java.awt.Color(255, 204, 102));
        txtIDDep.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtIDDep.setForeground(new java.awt.Color(236, 239, 244));
        txtIDDep.setBorder(null);
        txtIDDep.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtIDDep.setName(""); // NOI18N
        txtIDDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDDepActionPerformed(evt);
            }
        });
        txtIDDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDDepKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDDepKeyTyped(evt);
            }
        });
        panelesBordesRedondeados1.add(txtIDDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 100, 40));

        lblBtnSalir.setBackground(new java.awt.Color(59, 66, 82));
        lblBtnSalir.setPreferredSize(new java.awt.Dimension(132, 40));
        lblBtnSalir.setRoundBottomLeft(20);
        lblBtnSalir.setRoundBottomRight(20);
        lblBtnSalir.setRoundTopLeft(20);
        lblBtnSalir.setRoundTopRight(20);

        btnSalir.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSalirKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lblBtnSalirLayout = new javax.swing.GroupLayout(lblBtnSalir);
        lblBtnSalir.setLayout(lblBtnSalirLayout);
        lblBtnSalirLayout.setHorizontalGroup(
            lblBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBtnSalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lblBtnSalirLayout.setVerticalGroup(
            lblBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBtnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelesBordesRedondeados1.add(lblBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesBordesRedondeados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesBordesRedondeados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !txtEstado.getText().isEmpty()) {
            txtDescDep.requestFocus();
        }
    }//GEN-LAST:event_txtEstadoKeyPressed

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped

        txtDescDep.setEnabled(!txtEstado.getText().isEmpty());
    }//GEN-LAST:event_txtEstadoKeyTyped

    private void txtDescDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescDepActionPerformed

    }//GEN-LAST:event_txtDescDepActionPerformed

    private void txtDescDepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescDepKeyPressed

    }//GEN-LAST:event_txtDescDepKeyPressed

    private void txtDescDepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescDepKeyTyped

    }//GEN-LAST:event_txtDescDepKeyTyped

    private void btnInicioSesion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioSesion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesion1MouseClicked

    private void btnInicioSesion1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioSesion1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesion1MousePressed

    private void btnInicioSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesion1ActionPerformed

    private void btnInicioSesion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInicioSesion1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesion1KeyTyped

    private void btnInicioSesion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioSesion2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesion2MouseClicked

    private void btnInicioSesion2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioSesion2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesion2MousePressed

    private void btnInicioSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesion2ActionPerformed

    private void btnInicioSesion2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInicioSesion2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesion2KeyTyped

    private void txtIDDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDDepActionPerformed

    private void txtIDDepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDDepKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDDepKeyPressed

    private void txtIDDepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDDepKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDDepKeyTyped

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Departamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioSesion1;
    private javax.swing.JButton btnInicioSesion2;
    private javax.swing.JButton btnSalir;
    private Utilidades.PanelesBordesRedondeados lblBotonEliminar;
    private Utilidades.PanelesBordesRedondeados lblBotonRegistrar;
    private Utilidades.PanelesBordesRedondeados lblBtnSalir;
    private javax.swing.JLabel lblDescDep;
    private javax.swing.JLabel lblIDDep;
    private javax.swing.JLabel lblUsuario;
    private Utilidades.PanelesBordesRedondeados panelesBordesRedondeados1;
    private javax.swing.JSeparator sdrCampoDescDep;
    private javax.swing.JSeparator sdrIDDep;
    private javax.swing.JPasswordField txtDescDep;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIDDep;
    // End of variables declaration//GEN-END:variables
}
