/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mantenimientos;

import ManejoDeArchivos.ManejoArchivos;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Duanel
 */
public class Puestos extends javax.swing.JFrame {

    /**
     * Creates new form Departamentos
     */
    public Puestos() {
        initComponents();
        
        setTitle("Mantenimiento de Puestos");
        ImageIcon icono = new ImageIcon(getClass().getResource("/Iconos/ProgramIcon.png"));
        this.setIconImage(icono.getImage());

        setLocationRelativeTo(null); // Centra la ventana en la pantalla.
        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30)); //Redondea Bordes de la ventana Jframe
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Permite que solo se cierre la ventana

        //Colores Transparentes para los campos
        txtIDPuesto.setBackground(new Color(0, 0, 0, 0));
        txtDescPuesto.setBackground(new Color(0, 0, 0, 0));
        txtEstado.setBackground(new Color(0, 0, 0, 0));
    }

    public String buscar(String PuestosBuscado) {
        String lineaEncontrada = null;

        try {
            File archivo = new File("src/BaseDeDatos/Puestos.txt");
            BufferedReader br = new BufferedReader(new FileReader(archivo));
            String linea;

            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(";");
                if (partes.length >= 1 && partes[0].equalsIgnoreCase(PuestosBuscado.trim())) {
                    lineaEncontrada = linea;
                    br.close();
                    return lineaEncontrada;
                }
            }

            br.close();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al buscar el puesto: " + e.getMessage());
        }

        return null;
    }

    boolean encontrado = false;
    String cadenaAnterior = "";
    File archivo = new File("src/BaseDeDatos/Puestos.txt");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelesBordesRedondeados1 = new Utilidades.PanelesBordesRedondeados();
        sdrIDDep = new javax.swing.JSeparator();
        txtEstado = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblDescPuesto = new javax.swing.JLabel();
        sdrCampoDescDep = new javax.swing.JSeparator();
        lblIDPuesto = new javax.swing.JLabel();
        lblBotonRegistrar = new Utilidades.PanelesBordesRedondeados();
        btnRegistrar = new javax.swing.JButton();
        lblBotonEliminar = new Utilidades.PanelesBordesRedondeados();
        btnEliminar = new javax.swing.JButton();
        txtDescPuesto = new javax.swing.JTextField();
        lblBtnSalir = new Utilidades.PanelesBordesRedondeados();
        btnSalir = new javax.swing.JButton();
        txtIDPuesto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelesBordesRedondeados1.setBackground(new java.awt.Color(76, 86, 106));
        panelesBordesRedondeados1.setEnabled(false);
        panelesBordesRedondeados1.setFocusable(false);
        panelesBordesRedondeados1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelesBordesRedondeados1.add(sdrIDDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 100, 10));

        txtEstado.setEditable(false);
        txtEstado.setBackground(new java.awt.Color(255, 204, 102));
        txtEstado.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(236, 239, 244));
        txtEstado.setText("Creando");
        txtEstado.setBorder(null);
        txtEstado.setEnabled(false);
        txtEstado.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtEstado.setName(""); // NOI18N
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEstadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });
        panelesBordesRedondeados1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 100, 40));

        lblUsuario.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(236, 239, 244));
        lblUsuario.setText("Estado:");
        panelesBordesRedondeados1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        lblDescPuesto.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblDescPuesto.setForeground(new java.awt.Color(236, 239, 244));
        lblDescPuesto.setText("Desc. del puesto");
        panelesBordesRedondeados1.add(lblDescPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        panelesBordesRedondeados1.add(sdrCampoDescDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 240, 10));

        lblIDPuesto.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblIDPuesto.setForeground(new java.awt.Color(236, 239, 244));
        lblIDPuesto.setText("ID del puesto");
        panelesBordesRedondeados1.add(lblIDPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        lblBotonRegistrar.setBackground(new java.awt.Color(59, 66, 82));
        lblBotonRegistrar.setPreferredSize(new java.awt.Dimension(132, 40));
        lblBotonRegistrar.setRoundBottomLeft(20);
        lblBotonRegistrar.setRoundBottomRight(20);
        lblBotonRegistrar.setRoundTopLeft(20);
        lblBotonRegistrar.setRoundTopRight(20);

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistrarMousePressed(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        btnRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnRegistrarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lblBotonRegistrarLayout = new javax.swing.GroupLayout(lblBotonRegistrar);
        lblBotonRegistrar.setLayout(lblBotonRegistrarLayout);
        lblBotonRegistrarLayout.setHorizontalGroup(
            lblBotonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBotonRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lblBotonRegistrarLayout.setVerticalGroup(
            lblBotonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBotonRegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelesBordesRedondeados1.add(lblBotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        lblBotonEliminar.setBackground(new java.awt.Color(59, 66, 82));
        lblBotonEliminar.setPreferredSize(new java.awt.Dimension(132, 40));
        lblBotonEliminar.setRoundBottomLeft(20);
        lblBotonEliminar.setRoundBottomRight(20);
        lblBotonEliminar.setRoundTopLeft(20);
        lblBotonEliminar.setRoundTopRight(20);

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        btnEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnEliminarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lblBotonEliminarLayout = new javax.swing.GroupLayout(lblBotonEliminar);
        lblBotonEliminar.setLayout(lblBotonEliminarLayout);
        lblBotonEliminarLayout.setHorizontalGroup(
            lblBotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBotonEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lblBotonEliminarLayout.setVerticalGroup(
            lblBotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBotonEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelesBordesRedondeados1.add(lblBotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        txtDescPuesto.setBackground(new java.awt.Color(255, 204, 102));
        txtDescPuesto.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtDescPuesto.setForeground(new java.awt.Color(236, 239, 244));
        txtDescPuesto.setBorder(null);
        txtDescPuesto.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtDescPuesto.setName(""); // NOI18N
        txtDescPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescPuestoActionPerformed(evt);
            }
        });
        txtDescPuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescPuestoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescPuestoKeyTyped(evt);
            }
        });
        panelesBordesRedondeados1.add(txtDescPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, 40));

        lblBtnSalir.setBackground(new java.awt.Color(59, 66, 82));
        lblBtnSalir.setPreferredSize(new java.awt.Dimension(132, 40));
        lblBtnSalir.setRoundBottomLeft(20);
        lblBtnSalir.setRoundBottomRight(20);
        lblBtnSalir.setRoundTopLeft(20);
        lblBtnSalir.setRoundTopRight(20);

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSalirKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lblBtnSalirLayout = new javax.swing.GroupLayout(lblBtnSalir);
        lblBtnSalir.setLayout(lblBtnSalirLayout);
        lblBtnSalirLayout.setHorizontalGroup(
            lblBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBtnSalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lblBtnSalirLayout.setVerticalGroup(
            lblBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBtnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelesBordesRedondeados1.add(lblBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        txtIDPuesto.setBackground(new java.awt.Color(255, 204, 102));
        txtIDPuesto.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtIDPuesto.setForeground(new java.awt.Color(236, 239, 244));
        txtIDPuesto.setBorder(null);
        txtIDPuesto.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtIDPuesto.setName(""); // NOI18N
        txtIDPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPuestoActionPerformed(evt);
            }
        });
        txtIDPuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDPuestoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDPuestoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDPuestoKeyTyped(evt);
            }
        });
        panelesBordesRedondeados1.add(txtIDPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesBordesRedondeados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesBordesRedondeados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !txtEstado.getText().isEmpty()) {
            txtDescPuesto.requestFocus();
        }
    }//GEN-LAST:event_txtEstadoKeyPressed

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped

        txtDescPuesto.setEnabled(!txtEstado.getText().isEmpty());
    }//GEN-LAST:event_txtEstadoKeyTyped

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String IDPuesto = txtIDPuesto.getText().trim();
        
        if (IDPuesto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un puesto para eliminar.");
            return;
        }
        
        String lineaEncontrada = buscar(IDPuesto);
        
        if (lineaEncontrada == null) {
            JOptionPane.showMessageDialog(null, "El puesto no existe.");
            return;
        }
        
        String[] datos = lineaEncontrada.split(";");
        txtDescPuesto.setText(datos[1]);
        
        int confirmacion = JOptionPane.showConfirmDialog(
                null,
                "¿Está seguro de que desea eliminar el puesto '" + datos[1] + "'?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            ManejoArchivos manejo = new ManejoArchivos();

            try {
                
                manejo.Eliminar(lineaEncontrada, archivo);
                JOptionPane.showMessageDialog(null, "Puesto eliminado correctamente.");
                
                txtIDPuesto.setText("");
                txtDescPuesto.setText("");
                txtEstado.setText("Creando");
                
                encontrado = false;
                cadenaAnterior = "";
                
                txtDescPuesto.setEnabled(false);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al eliminar el puesto: " + ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEliminarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarKeyTyped

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarMousePressed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String IDPuesto = txtIDPuesto.getText().trim();
        String lineaExistente = buscar(IDPuesto);

        String DescPuesto = txtDescPuesto.getText().trim();


        if (IDPuesto.isEmpty() || DescPuesto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
            
        } else {

            if (!txtIDPuesto.getText().trim().matches("^\\d+$")) {
                JOptionPane.showMessageDialog(this, "El ID solo debe contener números.", "Dato inválido", JOptionPane.WARNING_MESSAGE);
                txtIDPuesto.requestFocus();
               
            } else if (!txtDescPuesto.getText().trim().matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s-]+$")) {
                JOptionPane.showMessageDialog(this, "La descripción solo debe contener letras, espacios o guiones.", "Dato inválido", JOptionPane.WARNING_MESSAGE);
                txtDescPuesto.requestFocus();
             
            } else {

                if (lineaExistente != null && !encontrado) {
                    JOptionPane.showMessageDialog(null, "El puesto ya existe. Presione ENTER para modificarlo.");
                    return;
                }
              
                String nuevaLinea = IDPuesto + ";" + DescPuesto;

                ManejoArchivos manejo = new ManejoArchivos();

                try {
                    if (!encontrado) {
                        // Guardar nuevo
                        manejo.GuardarDatos(nuevaLinea, archivo);
                        JOptionPane.showMessageDialog(null, "Puesto guardado correctamente.");
                    } else {
                        // Modificar usuario existente usando tu método Modificar
                        manejo.Modificar(cadenaAnterior, nuevaLinea, archivo);
                        JOptionPane.showMessageDialog(null, "Puesto modificado correctamente.");
                    }
                    
                    encontrado = false;
                    txtIDPuesto.setText("");
                    txtDescPuesto.setText("");

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al guardar: " + ex.getMessage());
                }

            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegistrarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarKeyTyped

    private void txtDescPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescPuestoActionPerformed

    private void txtDescPuestoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescPuestoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescPuestoKeyPressed

    private void txtDescPuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescPuestoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescPuestoKeyTyped

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirKeyTyped

    private void txtIDPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPuestoActionPerformed

    private void txtIDPuestoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDPuestoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPuestoKeyPressed

    private void txtIDPuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDPuestoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPuestoKeyTyped

    private void txtIDPuestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDPuestoKeyReleased
        String IDPuesto = txtIDPuesto.getText().trim();

        // Autocompletado: buscar y llenar campos automáticamente
        if (!IDPuesto.isEmpty()) {
            String lineaEncontrada = buscar(IDPuesto);

            if (lineaEncontrada != null) {
                
                String[] datos = lineaEncontrada.split(";");
                
                if (txtDescPuesto.getText().trim().isEmpty() || encontrado) {
                    txtDescPuesto.setText(datos[1]);
                }
                
                txtDescPuesto.setText(datos[1]);
                
                txtEstado.setText("Modificando");
                btnEliminar.setEnabled(true);
                encontrado = true;
                cadenaAnterior = lineaEncontrada;

            } else {

                if (!txtEstado.getText().equals("Creando")) {

                    txtDescPuesto.setText("");;

                    txtEstado.setText("Creando");
                    encontrado = false;
                    cadenaAnterior = "";
                    btnEliminar.setEnabled(false);
                }
            }
        } else {

            txtDescPuesto.setText("");
            txtEstado.setText("Creando");
            encontrado = false;
            cadenaAnterior = "";
        }

        if (IDPuesto.isEmpty()) {
            txtDescPuesto.setEnabled(false);
        } else {
            txtDescPuesto.setEnabled(true);

        }
    }//GEN-LAST:event_txtIDPuestoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private Utilidades.PanelesBordesRedondeados lblBotonEliminar;
    private Utilidades.PanelesBordesRedondeados lblBotonRegistrar;
    private Utilidades.PanelesBordesRedondeados lblBtnSalir;
    private javax.swing.JLabel lblDescPuesto;
    private javax.swing.JLabel lblIDPuesto;
    private javax.swing.JLabel lblUsuario;
    private Utilidades.PanelesBordesRedondeados panelesBordesRedondeados1;
    private javax.swing.JSeparator sdrCampoDescDep;
    private javax.swing.JSeparator sdrIDDep;
    private javax.swing.JTextField txtDescPuesto;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIDPuesto;
    // End of variables declaration//GEN-END:variables
}
