/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanaPrincipal;

import Login.Login;
import Mantenimientos.Usuarios;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author jhams
 */
public class Inicio extends javax.swing.JFrame {

    private String rolUsuario;

    /**
     * Creates new form Menu
     */
    public Inicio(String rol) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Coloca todo en pantalla completa
        ImageIcon icono = new ImageIcon(getClass().getResource("/Iconos/ProgramIcon.png"));
        this.setIconImage(icono.getImage());

        this.rolUsuario = rol;
        System.out.println(rolUsuario);

        if ("1".equals(rolUsuario)) {
            mniMantUsuarios.setEnabled(false);
            mnProcesos.setEnabled(false);
        } else {
            mniMantUsuarios.setEnabled(true);
            mnProcesos.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelesBordesRedondeados1 = new Utilidades.PanelesBordesRedondeados();
        jButton1 = new javax.swing.JButton();
        mnbMenu = new javax.swing.JMenuBar();
        mnMantenimientos = new javax.swing.JMenu();
        mniMantUsuarios = new javax.swing.JMenuItem();
        mniMantDepartamentos = new javax.swing.JMenuItem();
        mniMantPuestos = new javax.swing.JMenuItem();
        mniMantEmpleados = new javax.swing.JMenuItem();
        mnProcesos = new javax.swing.JMenu();
        mniProcGenerarNomina = new javax.swing.JMenuItem();
        mniProcReversarNomina = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        mniConsDepartamentos = new javax.swing.JMenuItem();
        mniConsPuestos = new javax.swing.JMenuItem();
        mniConsEmpleados = new javax.swing.JMenuItem();
        mniConsNominaXF = new javax.swing.JMenuItem();
        mniConsNominaXIDEmp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelesBordesRedondeados1.setBackground(new java.awt.Color(46, 52, 64));

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelesBordesRedondeados1Layout = new javax.swing.GroupLayout(panelesBordesRedondeados1);
        panelesBordesRedondeados1.setLayout(panelesBordesRedondeados1Layout);
        panelesBordesRedondeados1Layout.setHorizontalGroup(
            panelesBordesRedondeados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelesBordesRedondeados1Layout.createSequentialGroup()
                .addContainerGap(852, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        panelesBordesRedondeados1Layout.setVerticalGroup(
            panelesBordesRedondeados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelesBordesRedondeados1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(542, Short.MAX_VALUE))
        );

        mnbMenu.setBackground(new java.awt.Color(76, 86, 106));
        mnbMenu.setBorder(null);
        mnbMenu.setPreferredSize(new java.awt.Dimension(234, 40));

        mnMantenimientos.setText("Mantenimientos");
        mnMantenimientos.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
                mnMantenimientosMenuDragMouseEntered(evt);
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
        });

        mniMantUsuarios.setText("Usuarios");
        mniMantUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMantUsuariosActionPerformed(evt);
            }
        });
        mnMantenimientos.add(mniMantUsuarios);

        mniMantDepartamentos.setText("Departamentos");
        mniMantDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMantDepartamentosActionPerformed(evt);
            }
        });
        mnMantenimientos.add(mniMantDepartamentos);

        mniMantPuestos.setText("Puestos");
        mnMantenimientos.add(mniMantPuestos);

        mniMantEmpleados.setText("Empleados");
        mnMantenimientos.add(mniMantEmpleados);

        mnbMenu.add(mnMantenimientos);

        mnProcesos.setText("Procesos");

        mniProcGenerarNomina.setText("Generar nómina");
        mnProcesos.add(mniProcGenerarNomina);

        mniProcReversarNomina.setText("Reversar Nómina");
        mnProcesos.add(mniProcReversarNomina);

        mnbMenu.add(mnProcesos);

        mnConsultas.setText("Consultas");

        mniConsDepartamentos.setText("Departamentos");
        mnConsultas.add(mniConsDepartamentos);

        mniConsPuestos.setText("Puestos");
        mnConsultas.add(mniConsPuestos);

        mniConsEmpleados.setText("Empleados");
        mnConsultas.add(mniConsEmpleados);

        mniConsNominaXF.setText("Nómina por Fecha");
        mnConsultas.add(mniConsNominaXF);

        mniConsNominaXIDEmp.setText("Nómina por ID de Empleado");
        mnConsultas.add(mniConsNominaXIDEmp);

        mnbMenu.add(mnConsultas);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesBordesRedondeados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesBordesRedondeados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniMantDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMantDepartamentosActionPerformed
        TestDialog dialog = new TestDialog(Inicio.this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_mniMantDepartamentosActionPerformed

    private void mnMantenimientosMenuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_mnMantenimientosMenuDragMouseEntered
        // TODO add your handling code here
    }//GEN-LAST:event_mnMantenimientosMenuDragMouseEntered

    private Usuarios ventanaUsuarios = null;
    
    private void mniMantUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMantUsuariosActionPerformed
        if (ventanaUsuarios == null || !ventanaUsuarios.isDisplayable()) {
        ventanaUsuarios = new Usuarios();
        ventanaUsuarios.setVisible(true);
    } else {
        ventanaUsuarios.toFront(); // Trae la ventana al frente
        ventanaUsuarios.requestFocus(); // Le da el foco
    }
    }//GEN-LAST:event_mniMantUsuariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();

            Login ventanaLogin = new Login();
            ventanaLogin.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnMantenimientos;
    private javax.swing.JMenu mnProcesos;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniConsDepartamentos;
    private javax.swing.JMenuItem mniConsEmpleados;
    private javax.swing.JMenuItem mniConsNominaXF;
    private javax.swing.JMenuItem mniConsNominaXIDEmp;
    private javax.swing.JMenuItem mniConsPuestos;
    private javax.swing.JMenuItem mniMantDepartamentos;
    private javax.swing.JMenuItem mniMantEmpleados;
    private javax.swing.JMenuItem mniMantPuestos;
    private javax.swing.JMenuItem mniMantUsuarios;
    private javax.swing.JMenuItem mniProcGenerarNomina;
    private javax.swing.JMenuItem mniProcReversarNomina;
    private Utilidades.PanelesBordesRedondeados panelesBordesRedondeados1;
    // End of variables declaration//GEN-END:variables
}
