/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VentanaPrincipal;

import java.awt.Color;

/**
 *
 * @author Duanel
 */
public class TestDialog extends javax.swing.JDialog {

    /**
     * Creates new form TestDialog
     */
    public TestDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        txtUsuario.setBackground(new Color(0, 0, 0, 0));
        pwdContrasenia.setBackground(new Color(0, 0, 0, 0));
        txtNombre.setBackground(new Color(0, 0, 0, 0));
        txtApellido.setBackground(new Color(0, 0, 0, 0));
        txtCorreo.setBackground(new Color(0, 0, 0, 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new Utilidades.PanelesBordesRedondeados();
        sdrCampoUsuario = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        sdrCampoContrasenia = new javax.swing.JSeparator();
        pwdContrasenia = new javax.swing.JPasswordField();
        btnMostrarContrasenia = new javax.swing.JButton();
        lblRol = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        sdrCampoNombre = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        sdrCampoApellido = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        sdrCampoCorreo = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        lblContrasenia1 = new javax.swing.JLabel();
        pnlBotonRadiusAdmin = new Utilidades.PanelesBordesRedondeados();
        pnlBotonRadiusUser = new Utilidades.PanelesBordesRedondeados();
        lblRol1 = new javax.swing.JLabel();
        lblRol2 = new javax.swing.JLabel();
        lblBotonRegistrar = new Utilidades.PanelesBordesRedondeados();
        lblBotonLimpiar = new Utilidades.PanelesBordesRedondeados();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(46, 52, 64));
        setUndecorated(true);
        setSize(new java.awt.Dimension(400, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(76, 86, 106));
        pnlFondo.setRoundBottomLeft(30);
        pnlFondo.setRoundBottomRight(30);
        pnlFondo.setRoundTopLeft(30);
        pnlFondo.setRoundTopRight(30);
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFondo.add(sdrCampoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 240, 10));

        txtUsuario.setBackground(new java.awt.Color(255, 204, 102));
        txtUsuario.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(236, 239, 244));
        txtUsuario.setBorder(null);
        txtUsuario.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtUsuario.setName(""); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        pnlFondo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 240, 40));
        pnlFondo.add(sdrCampoContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 240, 10));

        pwdContrasenia.setBackground(new java.awt.Color(255, 0, 102));
        pwdContrasenia.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pwdContrasenia.setForeground(new java.awt.Color(236, 239, 244));
        pwdContrasenia.setBorder(null);
        pwdContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdContraseniaActionPerformed(evt);
            }
        });
        pwdContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdContraseniaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdContraseniaKeyTyped(evt);
            }
        });
        pnlFondo.add(pwdContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 240, 40));

        btnMostrarContrasenia.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        btnMostrarContrasenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/visibility_off.png"))); // NOI18N
        btnMostrarContrasenia.setBorder(null);
        btnMostrarContrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarContraseniaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMostrarContraseniaMouseReleased(evt);
            }
        });
        btnMostrarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarContraseniaActionPerformed(evt);
            }
        });
        pnlFondo.add(btnMostrarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 40, 40));

        lblRol.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblRol.setForeground(new java.awt.Color(236, 239, 244));
        lblRol.setText("Usuario");
        pnlFondo.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(236, 239, 244));
        lblUsuario.setText("Usuario");
        pnlFondo.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        lblNombre.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(236, 239, 244));
        lblNombre.setText("Nombre");
        pnlFondo.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));
        pnlFondo.add(sdrCampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 270, 10));

        txtNombre.setBackground(new java.awt.Color(255, 204, 102));
        txtNombre.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(236, 239, 244));
        txtNombre.setBorder(null);
        txtNombre.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtNombre.setName(""); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        pnlFondo.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 270, 40));

        lblApellido.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(236, 239, 244));
        lblApellido.setText("Apellido");
        pnlFondo.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));
        pnlFondo.add(sdrCampoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 270, 10));

        txtApellido.setBackground(new java.awt.Color(255, 204, 102));
        txtApellido.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(236, 239, 244));
        txtApellido.setBorder(null);
        txtApellido.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtApellido.setName(""); // NOI18N
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        pnlFondo.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 270, 40));

        lblCorreo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(236, 239, 244));
        lblCorreo.setText("Correo");
        pnlFondo.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));
        pnlFondo.add(sdrCampoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 270, 10));

        txtCorreo.setBackground(new java.awt.Color(255, 204, 102));
        txtCorreo.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(236, 239, 244));
        txtCorreo.setBorder(null);
        txtCorreo.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtCorreo.setName(""); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        pnlFondo.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 270, 40));

        lblContrasenia1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblContrasenia1.setForeground(new java.awt.Color(236, 239, 244));
        lblContrasenia1.setText("Contraseña");
        pnlFondo.add(lblContrasenia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        pnlBotonRadiusAdmin.setPreferredSize(new java.awt.Dimension(25, 25));
        pnlBotonRadiusAdmin.setRoundBottomLeft(25);
        pnlBotonRadiusAdmin.setRoundBottomRight(25);
        pnlBotonRadiusAdmin.setRoundTopLeft(25);
        pnlBotonRadiusAdmin.setRoundTopRight(25);

        javax.swing.GroupLayout pnlBotonRadiusAdminLayout = new javax.swing.GroupLayout(pnlBotonRadiusAdmin);
        pnlBotonRadiusAdmin.setLayout(pnlBotonRadiusAdminLayout);
        pnlBotonRadiusAdminLayout.setHorizontalGroup(
            pnlBotonRadiusAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlBotonRadiusAdminLayout.setVerticalGroup(
            pnlBotonRadiusAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        pnlFondo.add(pnlBotonRadiusAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        pnlBotonRadiusUser.setPreferredSize(new java.awt.Dimension(25, 25));
        pnlBotonRadiusUser.setRoundBottomLeft(25);
        pnlBotonRadiusUser.setRoundBottomRight(25);
        pnlBotonRadiusUser.setRoundTopLeft(25);
        pnlBotonRadiusUser.setRoundTopRight(25);

        javax.swing.GroupLayout pnlBotonRadiusUserLayout = new javax.swing.GroupLayout(pnlBotonRadiusUser);
        pnlBotonRadiusUser.setLayout(pnlBotonRadiusUserLayout);
        pnlBotonRadiusUserLayout.setHorizontalGroup(
            pnlBotonRadiusUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlBotonRadiusUserLayout.setVerticalGroup(
            pnlBotonRadiusUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        pnlFondo.add(pnlBotonRadiusUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        lblRol1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblRol1.setForeground(new java.awt.Color(236, 239, 244));
        lblRol1.setText("Rol");
        pnlFondo.add(lblRol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        lblRol2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblRol2.setForeground(new java.awt.Color(236, 239, 244));
        lblRol2.setText("Adminstrador");
        pnlFondo.add(lblRol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        lblBotonRegistrar.setPreferredSize(new java.awt.Dimension(132, 40));
        lblBotonRegistrar.setRoundBottomLeft(20);
        lblBotonRegistrar.setRoundBottomRight(20);
        lblBotonRegistrar.setRoundTopLeft(20);
        lblBotonRegistrar.setRoundTopRight(20);

        javax.swing.GroupLayout lblBotonRegistrarLayout = new javax.swing.GroupLayout(lblBotonRegistrar);
        lblBotonRegistrar.setLayout(lblBotonRegistrarLayout);
        lblBotonRegistrarLayout.setHorizontalGroup(
            lblBotonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        lblBotonRegistrarLayout.setVerticalGroup(
            lblBotonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnlFondo.add(lblBotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        lblBotonLimpiar.setPreferredSize(new java.awt.Dimension(132, 40));
        lblBotonLimpiar.setRoundBottomLeft(20);
        lblBotonLimpiar.setRoundBottomRight(20);
        lblBotonLimpiar.setRoundTopLeft(20);
        lblBotonLimpiar.setRoundTopRight(20);

        javax.swing.GroupLayout lblBotonLimpiarLayout = new javax.swing.GroupLayout(lblBotonLimpiar);
        lblBotonLimpiar.setLayout(lblBotonLimpiarLayout);
        lblBotonLimpiarLayout.setHorizontalGroup(
            lblBotonLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        lblBotonLimpiarLayout.setVerticalGroup(
            lblBotonLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnlFondo.add(lblBotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !txtUsuario.getText().isEmpty()) {
            pwdContrasenia.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped

        pwdContrasenia.setEnabled(!txtUsuario.getText().isEmpty());
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void pwdContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContraseniaActionPerformed

    }//GEN-LAST:event_pwdContraseniaActionPerformed

    private void pwdContraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdContraseniaKeyPressed
       
    }//GEN-LAST:event_pwdContraseniaKeyPressed

    private void pwdContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdContraseniaKeyTyped
       
    }//GEN-LAST:event_pwdContraseniaKeyTyped

    private void btnMostrarContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarContraseniaMousePressed

    }//GEN-LAST:event_btnMostrarContraseniaMousePressed

    private void btnMostrarContraseniaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarContraseniaMouseReleased
       
    }//GEN-LAST:event_btnMostrarContraseniaMouseReleased

    private void btnMostrarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarContraseniaActionPerformed
        
    }//GEN-LAST:event_btnMostrarContraseniaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TestDialog dialog = new TestDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarContrasenia;
    private javax.swing.JLabel lblApellido;
    private Utilidades.PanelesBordesRedondeados lblBotonLimpiar;
    private Utilidades.PanelesBordesRedondeados lblBotonRegistrar;
    private javax.swing.JLabel lblContrasenia1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblRol1;
    private javax.swing.JLabel lblRol2;
    private javax.swing.JLabel lblUsuario;
    private Utilidades.PanelesBordesRedondeados pnlBotonRadiusAdmin;
    private Utilidades.PanelesBordesRedondeados pnlBotonRadiusUser;
    private Utilidades.PanelesBordesRedondeados pnlFondo;
    private javax.swing.JPasswordField pwdContrasenia;
    private javax.swing.JSeparator sdrCampoApellido;
    private javax.swing.JSeparator sdrCampoContrasenia;
    private javax.swing.JSeparator sdrCampoCorreo;
    private javax.swing.JSeparator sdrCampoNombre;
    private javax.swing.JSeparator sdrCampoUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
