/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import VentanaPrincipal.Inicio;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author jhams
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    ImageIcon iconoNormal = new ImageIcon(Login.class.getResource("/Iconos/visibility_off.png"));
    ImageIcon iconoPresionado = new ImageIcon(Login.class.getResource("/Iconos/visibility.png"));

    private int xMouse, yMouse;
    
    private String rolUsuarioActual = "";
    
    public String obtenerRolUsuarioActual() {
        return rolUsuarioActual;
    }
    

    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_SMOOTH)
        );
        labelName.setIcon(icon);
        this.repaint();
    }

    public Login() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana en la pantalla.
        
        btnInicioSesion.setEnabled(!txtUsuario.getText().isEmpty());

        String contrasenia = new String(pwdContrasenia.getPassword());
        btnMostrarContrasenia.setEnabled(!contrasenia.isEmpty());

        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30)); //Redondea Bordes de la ventana Jframe

        txtUsuario.setBackground(new Color(0, 0, 0, 0));
        pwdContrasenia.setBackground(new Color(0, 0, 0, 0));
        btnMostrarContrasenia.setBackground(new Color(0, 0, 0, 0));
        btnInicioSesion.setBackground(new Color(0, 0, 0, 0));
        pnlImagenFondo.setBackground(new Color (0, 0, 0, 0));

        SetImageLabel(txtUserIcon, "src/Iconos/img_User_Login_400x400.png");
        SetImageLabel(txtImagenFondo, "src/Imágenes/ImagenFondo.png");
        SetImageLabel(txtUserAcc, "src/Iconos/account_user.png");
        SetImageLabel(txtUserPwd, "src/Iconos/pwd_Ico.png");
        
        ImageIcon icono = new ImageIcon(getClass().getResource("/Iconos/ProgramIcon.png"));
        this.setIconImage(icono.getImage());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new org.netbeans.modules.form.InvalidComponent();
        pnlImagenFondo = new org.netbeans.modules.form.InvalidComponent();
        txtImagenFondo = new javax.swing.JLabel();
        pnlFormularioLogin = new org.netbeans.modules.form.InvalidComponent();
        sdrCampoContrasenia = new javax.swing.JSeparator();
        pwdContrasenia = new javax.swing.JPasswordField();
        sdrCampoUsuario = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        btnMostrarContrasenia = new javax.swing.JButton();
        pnlBotonIniciarSesion = new org.netbeans.modules.form.InvalidComponent();
        btnInicioSesion = new javax.swing.JButton();
        txtUserPwd = new javax.swing.JLabel();
        txtUserAcc = new javax.swing.JLabel();
        pntlIconoUsuario = new org.netbeans.modules.form.InvalidComponent();
        txtUserIcon = new javax.swing.JLabel();
        pnlBarraTitulo = new org.netbeans.modules.form.InvalidComponent();
        pnlBotonSalir = new org.netbeans.modules.form.InvalidComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(46, 52, 64));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlImagenFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlImagenFondo.add(txtImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 490));

        pnlFondo.add(pnlImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 470, 490));

        pnlFormularioLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFormularioLogin.add(sdrCampoContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 123, 240, 10));

        pwdContrasenia.setBackground(new java.awt.Color(255, 0, 102));
        pwdContrasenia.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pwdContrasenia.setForeground(new java.awt.Color(236, 239, 244));
        pwdContrasenia.setBorder(null);
        pwdContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdContraseniaActionPerformed(evt);
            }
        });
        pwdContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdContraseniaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdContraseniaKeyTyped(evt);
            }
        });
        pnlFormularioLogin.add(pwdContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 240, 40));
        pnlFormularioLogin.add(sdrCampoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 63, 240, 10));

        txtUsuario.setBackground(new java.awt.Color(255, 204, 102));
        txtUsuario.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(236, 239, 244));
        txtUsuario.setBorder(null);
        txtUsuario.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtUsuario.setName(""); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        pnlFormularioLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 240, 40));

        btnMostrarContrasenia.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        btnMostrarContrasenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/visibility_off.png"))); // NOI18N
        btnMostrarContrasenia.setBorder(null);
        btnMostrarContrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarContraseniaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMostrarContraseniaMouseReleased(evt);
            }
        });
        btnMostrarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarContraseniaActionPerformed(evt);
            }
        });
        pnlFormularioLogin.add(btnMostrarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 40, 40));

        btnInicioSesion.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnInicioSesion.setForeground(new java.awt.Color(204, 204, 204));
        btnInicioSesion.setText("Iniciar Sesión");
        btnInicioSesion.setBorder(null);
        btnInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioSesionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInicioSesionMousePressed(evt);
            }
        });
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        btnInicioSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnInicioSesionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonIniciarSesionLayout = new javax.swing.GroupLayout(pnlBotonIniciarSesion);
        pnlBotonIniciarSesion.setLayout(pnlBotonIniciarSesionLayout);
        pnlBotonIniciarSesionLayout.setHorizontalGroup(
            pnlBotonIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonIniciarSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotonIniciarSesionLayout.setVerticalGroup(
            pnlBotonIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonIniciarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlFormularioLogin.add(pnlBotonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 130, 40));
        pnlFormularioLogin.add(txtUserPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 93, 30, 30));
        pnlFormularioLogin.add(txtUserAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 33, 30, 30));

        pnlFondo.add(pnlFormularioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 380, 360));

        pntlIconoUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pntlIconoUsuario.add(txtUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        pnlFondo.add(pntlIconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 110, 110));

        pnlBarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlBotonSalirLayout = new javax.swing.GroupLayout(pnlBotonSalir);
        pnlBotonSalir.setLayout(pnlBotonSalirLayout);
        pnlBotonSalirLayout.setHorizontalGroup(
            pnlBotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnlBotonSalirLayout.setVerticalGroup(
            pnlBotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlBarraTitulo.add(pnlBotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 18, -1, 20));

        pnlFondo.add(pnlBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 50));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 910, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarCampos() {
        String contrasenia = new String(pwdContrasenia.getPassword());

        boolean habilitar = !txtUsuario.getText().isEmpty() && !contrasenia.isEmpty();
        btnInicioSesion.setEnabled(habilitar);
    }

    private boolean iniciarSesion() {
        String usuario = txtUsuario.getText();
        String contrasenia = new String(pwdContrasenia.getPassword());
        boolean encontrado = false;

        try {
            File f = new File("src/BaseDeDatos/Usuarios.txt");
            Scanner s = new Scanner(f);

            if (f.exists()) {
                while (s.hasNextLine() && !encontrado) {
                    String linea = s.nextLine();
                    Scanner s1 = new Scanner(linea);
                    s1.useDelimiter("\\s*;\\s*");

                    String usuarioGuardado = s1.next();
                    String contraseniaGuardada = s1.next();
                    String rolUsuario = s1.next();

                    if (usuario.equals(usuarioGuardado)) {
                        encontrado = true;
                        if (contrasenia.equals(contraseniaGuardada)) {
                            rolUsuarioActual = rolUsuario;
                            this.dispose();
                            Inicio MenuPrincipal = new Inicio(rolUsuarioActual);
                            MenuPrincipal.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta");
                            pwdContrasenia.setText("");
                        }
                    }
                }
                s.close();

                if (!encontrado) {
                    JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado");
                    txtUsuario.setText("");
                    pwdContrasenia.setText("");
                    txtUsuario.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "No existe el archivo de usuarios");
            }
        } catch (HeadlessException | FileNotFoundException e) {
            System.out.println("Error al leer el archivo: " + e);
            JOptionPane.showMessageDialog(rootPane, "Error al leer los datos");
        }
        return false;
    }

    private void pnlBotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pnlBotonSalirMouseClicked

    private void pnlBotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonSalirMouseEntered
        pnlBotonSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnlBotonSalirMouseEntered

    private void pnlBarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);


    }//GEN-LAST:event_pnlBarraTituloMouseDragged

    private void pnlBarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlBarraTituloMousePressed

    private void btnMostrarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarContraseniaActionPerformed

    }//GEN-LAST:event_btnMostrarContraseniaActionPerformed

    private void btnMostrarContraseniaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarContraseniaMouseReleased
        pwdContrasenia.setEchoChar('•');
        btnMostrarContrasenia.setIcon(iconoNormal);
    }//GEN-LAST:event_btnMostrarContraseniaMouseReleased

    private void btnMostrarContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarContraseniaMousePressed
        String contrasenia = new String(pwdContrasenia.getPassword());
        if(!contrasenia.isEmpty()) {
            pwdContrasenia.setEchoChar((char) 0);
            btnMostrarContrasenia.setIcon(iconoPresionado);
        }
    }//GEN-LAST:event_btnMostrarContraseniaMousePressed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped

        pwdContrasenia.setEnabled(!txtUsuario.getText().isEmpty());

        validarCampos();
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !txtUsuario.getText().isEmpty()) {
            pwdContrasenia.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void pwdContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdContraseniaKeyTyped
        String contrasenia = new String(pwdContrasenia.getPassword());
        btnMostrarContrasenia.setEnabled(!contrasenia.isEmpty());

        if(!contrasenia.isEmpty()) {
            pnlBotonIniciarSesion.setBackground(new Color(143, 188, 187));
            btnInicioSesion.setForeground(new Color(236, 239, 244));
        } else {
            pnlBotonIniciarSesion.setBackground(new Color(59, 66, 82));
            btnInicioSesion.setForeground(new Color(204,204,204));
        }

        validarCampos();
    }//GEN-LAST:event_pwdContraseniaKeyTyped

    private void pwdContraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdContraseniaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !pwdContrasenia.getText().isEmpty()) {
            if (iniciarSesion()) {
                this.dispose();

                Inicio MenuPrincipal = new Inicio(rolUsuarioActual);
                MenuPrincipal.setVisible(true);
            }
        }
    }//GEN-LAST:event_pwdContraseniaKeyPressed

    private void pwdContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContraseniaActionPerformed

    }//GEN-LAST:event_pwdContraseniaActionPerformed

    private void btnInicioSesionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInicioSesionKeyTyped
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !pwdContrasenia.getText().isEmpty()) {
            if (iniciarSesion()) {
                this.dispose();

                Inicio MenuPrincipal = new Inicio(rolUsuarioActual);
                MenuPrincipal.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnInicioSesionKeyTyped

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        if (iniciarSesion()) {
            this.dispose();

            Inicio MenuPrincipal = new Inicio(rolUsuarioActual);
            MenuPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnInicioSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioSesionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesionMousePressed

    private void btnInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioSesionMouseClicked

    }//GEN-LAST:event_btnInicioSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnMostrarContrasenia;
    private org.netbeans.modules.form.InvalidComponent pnlBarraTitulo;
    private org.netbeans.modules.form.InvalidComponent pnlBotonIniciarSesion;
    private org.netbeans.modules.form.InvalidComponent pnlBotonSalir;
    private org.netbeans.modules.form.InvalidComponent pnlFondo;
    private org.netbeans.modules.form.InvalidComponent pnlFormularioLogin;
    private org.netbeans.modules.form.InvalidComponent pnlImagenFondo;
    private org.netbeans.modules.form.InvalidComponent pntlIconoUsuario;
    private javax.swing.JPasswordField pwdContrasenia;
    private javax.swing.JSeparator sdrCampoContrasenia;
    private javax.swing.JSeparator sdrCampoUsuario;
    private javax.swing.JLabel txtImagenFondo;
    private javax.swing.JLabel txtUserAcc;
    private javax.swing.JLabel txtUserIcon;
    private javax.swing.JLabel txtUserPwd;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
