/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import VentanaPrincipal.Inicio;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jhams
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    ImageIcon iconoNormal = new ImageIcon(Login.class.getResource("/Iconos/visibility_off.png"));
    ImageIcon iconoPresionado = new ImageIcon(Login.class.getResource("/Iconos/visibility.png"));

    int xMouse, yMouse;

    public Login() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana en la pantalla.

        pwdContrasenia.setEnabled(!txtUsuario.getText().isEmpty());
        btnInicioSesion.setEnabled(!txtUsuario.getText().isEmpty());

        String contrasenia = new String(pwdContrasenia.getPassword());
        btnMostrarContrasenia.setEnabled(!contrasenia.isEmpty());

        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20)); //Redondea Bordes de la ventana Jframe
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlImagen = new javax.swing.JPanel();
        pnlBarraEstado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInicioSesion = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        btnMostrarContrasenia = new javax.swing.JButton();
        pwdContrasenia = new javax.swing.JPasswordField();
        txtBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(49, 55, 68));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlImagenLayout = new javax.swing.GroupLayout(pnlImagen);
        pnlImagen.setLayout(pnlImagenLayout);
        pnlImagenLayout.setHorizontalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        pnlImagenLayout.setVerticalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlFondo.add(pnlImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 480, 440));

        pnlBarraEstado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlBarraEstadoMouseDragged(evt);
            }
        });
        pnlBarraEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBarraEstadoMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBarraEstadoLayout = new javax.swing.GroupLayout(pnlBarraEstado);
        pnlBarraEstado.setLayout(pnlBarraEstadoLayout);
        pnlBarraEstadoLayout.setHorizontalGroup(
            pnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraEstadoLayout.createSequentialGroup()
                .addContainerGap(814, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBarraEstadoLayout.setVerticalGroup(
            pnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlFondo.add(pnlBarraEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 50));

        btnInicioSesion.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnInicioSesion.setText("Iniciar Sesión");
        btnInicioSesion.setBorder(null);
        btnInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        btnInicioSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnInicioSesionKeyTyped(evt);
            }
        });
        pnlFondo.add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, 40));

        txtUsuario.setBackground(new java.awt.Color(255, 102, 102));
        txtUsuario.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(200, 200, 200));
        txtUsuario.setToolTipText("Ingresa un usuario válido");
        txtUsuario.setBorder(null);
        txtUsuario.setName(""); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        pnlFondo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 330, 42));

        btnMostrarContrasenia.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        btnMostrarContrasenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/visibility_off.png"))); // NOI18N
        btnMostrarContrasenia.setBorder(null);
        btnMostrarContrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarContraseniaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMostrarContraseniaMouseReleased(evt);
            }
        });
        btnMostrarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarContraseniaActionPerformed(evt);
            }
        });
        pnlFondo.add(btnMostrarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 40, 44));

        pwdContrasenia.setBackground(new java.awt.Color(255, 102, 102));
        pwdContrasenia.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pwdContrasenia.setForeground(new java.awt.Color(200, 200, 200));
        pwdContrasenia.setToolTipText("Ingresa una contraseña válida");
        pwdContrasenia.setBorder(null);
        pwdContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdContraseniaActionPerformed(evt);
            }
        });
        pwdContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdContraseniaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdContraseniaKeyTyped(evt);
            }
        });
        pnlFondo.add(pwdContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 280, 44));

        txtBienvenida.setBackground(new java.awt.Color(0, 0, 0));
        txtBienvenida.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        txtBienvenida.setForeground(new java.awt.Color(236, 239, 244));
        txtBienvenida.setText("Bienvenido");
        pnlFondo.add(txtBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarCampos() {
        String contrasenia = new String(pwdContrasenia.getPassword());

        boolean habilitar = !txtUsuario.getText().isEmpty() && !contrasenia.isEmpty();
        btnInicioSesion.setEnabled(habilitar);
    }

    private boolean iniciarSesion() {
        String usuario = txtUsuario.getText();
        String contrasenia = new String(pwdContrasenia.getPassword());
        boolean encontrado = false;

        try {
            File f = new File("BaseDeDatos/Usuarios.txt");
            Scanner s = new Scanner(f);

            if (f.exists()) {
                while (s.hasNextLine() && !encontrado) {
                    String linea = s.nextLine();
                    Scanner s1 = new Scanner(linea);
                    s1.useDelimiter("\\s*;\\s*");

                    String usuarioGuardado = s1.next();
                    String contraseniaGuardada = s1.next();

                    if (usuario.equals(usuarioGuardado)) {
                        encontrado = true;
                        if (contrasenia.equals(contraseniaGuardada)) {
                            this.dispose();
                            Inicio MenuPrincipal = new Inicio();
                            MenuPrincipal.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta");
                            pwdContrasenia.setText("");
                        }
                    }
                }
                s.close();

                if (!encontrado) {
                    JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado");
                    txtUsuario.setText("");
                    pwdContrasenia.setText("");
                    txtUsuario.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "No existe el archivo de usuarios");
            }
        } catch (HeadlessException | FileNotFoundException e) {
            System.out.println("Error al leer el archivo: " + e);
            JOptionPane.showMessageDialog(rootPane, "Error al leer los datos");
        }
        return false;
    }

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !txtUsuario.getText().isEmpty()) {
            pwdContrasenia.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void pwdContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContraseniaActionPerformed

    }//GEN-LAST:event_pwdContraseniaActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped

        pwdContrasenia.setEnabled(!txtUsuario.getText().isEmpty());

        validarCampos();
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        if (iniciarSesion()) {
                this.dispose();

                Inicio MenuPrincipal = new Inicio();
                MenuPrincipal.setVisible(true);
            }
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void pwdContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdContraseniaKeyTyped
        String contrasenia = new String(pwdContrasenia.getPassword());
        btnMostrarContrasenia.setEnabled(!contrasenia.isEmpty());

        validarCampos();
    }//GEN-LAST:event_pwdContraseniaKeyTyped

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void pwdContraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdContraseniaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !pwdContrasenia.getText().isEmpty()) {
            if (iniciarSesion()) {
                this.dispose();

                Inicio MenuPrincipal = new Inicio();
                MenuPrincipal.setVisible(true);
            }
        }
    }//GEN-LAST:event_pwdContraseniaKeyPressed

    private void btnMostrarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarContraseniaActionPerformed


    }//GEN-LAST:event_btnMostrarContraseniaActionPerformed

    private void pnlBarraEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBarraEstadoMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlBarraEstadoMousePressed

    private void pnlBarraEstadoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBarraEstadoMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pnlBarraEstadoMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnMostrarContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarContraseniaMousePressed
        pwdContrasenia.setEchoChar((char) 0);
        btnMostrarContrasenia.setIcon(iconoPresionado);
    }//GEN-LAST:event_btnMostrarContraseniaMousePressed

    private void btnMostrarContraseniaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarContraseniaMouseReleased
        pwdContrasenia.setEchoChar('•');
        btnMostrarContrasenia.setIcon(iconoNormal);
    }//GEN-LAST:event_btnMostrarContraseniaMouseReleased

    private void btnInicioSesionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInicioSesionKeyTyped
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && !pwdContrasenia.getText().isEmpty()) {
            if (iniciarSesion()) {
                this.dispose();

                Inicio MenuPrincipal = new Inicio();
                MenuPrincipal.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnInicioSesionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnMostrarContrasenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBarraEstado;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlImagen;
    private javax.swing.JPasswordField pwdContrasenia;
    private javax.swing.JLabel txtBienvenida;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
