/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Consultas;

import ManejoDeArchivos.ManejoArchivos;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; // Asegúrate de importar esto

/**
 *
 * @author jhams
 */
public class Puestos extends javax.swing.JFrame {

    /**
     * Creates new form Departamentos
     */
    
     private File archivoDepartamentos = new File("src/BaseDeDatos/Puestos.txt");

    public Puestos() {
        initComponents();
       
        txtBuscador.setBackground(new Color(0, 0, 0, 0));
        txtEstado.setBackground(new Color(0, 0, 0, 0));

        // Cargar todos los departamentos al iniciar
        cargarPuestosEnTabla(""); 
    }
    
    private void cargarPuestosEnTabla(String filtro) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Puesto");
        modelo.addColumn("Descripción");

        TablePuestos.setModel(modelo);

        try (BufferedReader br = new BufferedReader(new FileReader(archivoDepartamentos))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(";");
                if (partes.length >= 2) { 
                    String id = partes[0].trim();
                    String descripcion = partes[1].trim();

                    // Convertir el filtro y los datos a minúsculas para una búsqueda insensible a mayúsculas
                    if (filtro.isEmpty() || 
                        id.toLowerCase().contains(filtro.toLowerCase()) || 
                        descripcion.toLowerCase().contains(filtro.toLowerCase())) {
                        
                        modelo.addRow(new Object[]{id, descripcion});
                    }
                }
            }
            // Actualizar el estado de la búsqueda
            if (filtro.isEmpty()) {
                txtEstado.setText("Mostrando " + modelo.getRowCount() + " puestos");
            } else {
                txtEstado.setText("Resultados para '" + filtro + "': " + modelo.getRowCount());
            }
            if (modelo.getRowCount() == 0 && !filtro.isEmpty()) {
                txtEstado.setText("No se encontraron resultados para '" + filtro + "'");
            }


        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar puestos: " + e.getMessage(), "Error de Archivo", JOptionPane.ERROR_MESSAGE);
            txtEstado.setText("Error al cargar datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelesBordesRedondeados1 = new Utilidades.PanelesBordesRedondeados();
        lblBuscador = new javax.swing.JLabel();
        sdrCampoDescDep = new javax.swing.JSeparator();
        txtBuscador = new javax.swing.JTextField();
        lblBtnSalir1 = new Utilidades.PanelesBordesRedondeados();
        btnSalir1 = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        ScrollPanePuestos = new javax.swing.JScrollPane();
        TablePuestos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelesBordesRedondeados1.setBackground(new java.awt.Color(76, 86, 106));
        panelesBordesRedondeados1.setEnabled(false);
        panelesBordesRedondeados1.setFocusable(false);
        panelesBordesRedondeados1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscador.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblBuscador.setForeground(new java.awt.Color(236, 239, 244));
        lblBuscador.setText("Buscador");
        panelesBordesRedondeados1.add(lblBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        panelesBordesRedondeados1.add(sdrCampoDescDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 240, 10));

        txtBuscador.setBackground(new java.awt.Color(255, 204, 102));
        txtBuscador.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(236, 239, 244));
        txtBuscador.setBorder(null);
        txtBuscador.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtBuscador.setName(""); // NOI18N
        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyTyped(evt);
            }
        });
        panelesBordesRedondeados1.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 240, 40));

        lblBtnSalir1.setBackground(new java.awt.Color(59, 66, 82));
        lblBtnSalir1.setPreferredSize(new java.awt.Dimension(132, 40));
        lblBtnSalir1.setRoundBottomLeft(20);
        lblBtnSalir1.setRoundBottomRight(20);
        lblBtnSalir1.setRoundTopLeft(20);
        lblBtnSalir1.setRoundTopRight(20);

        btnSalir1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir1.setText("Salir");
        btnSalir1.setBorder(null);
        btnSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalir1MousePressed(evt);
            }
        });
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        btnSalir1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSalir1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lblBtnSalir1Layout = new javax.swing.GroupLayout(lblBtnSalir1);
        lblBtnSalir1.setLayout(lblBtnSalir1Layout);
        lblBtnSalir1Layout.setHorizontalGroup(
            lblBtnSalir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBtnSalir1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lblBtnSalir1Layout.setVerticalGroup(
            lblBtnSalir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBtnSalir1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelesBordesRedondeados1.add(lblBtnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        lblEstado.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(236, 239, 244));
        lblEstado.setText("Estado:");
        panelesBordesRedondeados1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, -1));

        txtEstado.setEditable(false);
        txtEstado.setBackground(new java.awt.Color(255, 204, 102));
        txtEstado.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(236, 239, 244));
        txtEstado.setText("Buscando");
        txtEstado.setBorder(null);
        txtEstado.setEnabled(false);
        txtEstado.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtEstado.setName(""); // NOI18N
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEstadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });
        panelesBordesRedondeados1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 240, 40));

        TablePuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPanePuestos.setViewportView(TablePuestos);

        panelesBordesRedondeados1.add(ScrollPanePuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 590, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesBordesRedondeados1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelesBordesRedondeados1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void txtBuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorKeyPressed

    private void txtBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorKeyTyped

    private void btnSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1MouseClicked

    private void btnSalir1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1MousePressed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnSalir1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalir1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1KeyTyped

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyPressed
       
    }//GEN-LAST:event_txtEstadoKeyPressed

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped

     
    }//GEN-LAST:event_txtEstadoKeyTyped

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        // TODO add your handling code here:
        String textoBusqueda = txtBuscador.getText().trim();
        cargarPuestosEnTabla(textoBusqueda);
    }//GEN-LAST:event_txtBuscadorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPanePuestos;
    private javax.swing.JTable TablePuestos;
    private javax.swing.JButton btnSalir1;
    private Utilidades.PanelesBordesRedondeados lblBtnSalir1;
    private javax.swing.JLabel lblBuscador;
    private javax.swing.JLabel lblEstado;
    private Utilidades.PanelesBordesRedondeados panelesBordesRedondeados1;
    private javax.swing.JSeparator sdrCampoDescDep;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtEstado;
    // End of variables declaration//GEN-END:variables
}
